# Generated by Django 2.2.6 on 2019-11-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flickermeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broadband', models.FloatField()),
                ('Infrared', models.FloatField()),
                ('Illuminance', models.FloatField()),
                ('FlickerModulation', models.FloatField()),
                ('FlickerIndex', models.FloatField()),
                ('LongFlickerModulation', models.FloatField()),
                ('LongFlickerIndex', models.FloatField()),
                ('Luminance', models.FloatField()),
                ('Flux', models.FloatField()),
                ('Time', models.FloatField()),
                ('LightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flickermeter.LightI')),
            ],
        ),
    ]
