# Generated by Django 2.2.7 on 2019-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flickermeter', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='VisibleLight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
